Mandatory1_MovieCatalog/Controllers/MovieController.cs
using Mandatory1_MovieCatalog.Models;
using Mandatory1_MovieCatalog.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mandatory1_MovieCatalog.Controllers
{
    public class MovieController : Controller
    {
        //quick - and dirty - D.I. later
        ApplicationDbContext db = new ApplicationDbContext();
        MovieRepository movieRepo = new MovieRepository();
        
        // GET: Movie
        public ActionResult Index()
        {
            return View(db.Movies.ToList());
        }

        // Display the view containing the create form
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // Update the db with the user input from the create form
        
        [HttpPost]
        public ActionResult CreateConfirmed(MovieModel movie)
        {
            //if(ModelState.IsValid)
            //{
                movieRepo.Insert(movie);
                return RedirectToAction("Index");
            //}
           
           // return View();

        }

        // Show the Edit view with the field info from the selected movie
        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Find the student from the id and send to view.
            return View(movieRepo.Find(id));
        }

        // Update db with the info provided by user in the edit view
        [HttpPost]
        public ActionResult EditConfirmed(MovieModel movie)
        {
            if(ModelState.IsValid)
            {
                movieRepo.Update(movie);
                return RedirectToAction("Index"); //go back to index-view after succesful edit
            }
            return View();
        }

        // Show view containing details for the entry that is going to be deleted
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(movieRepo.Find(id));
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            movieRepo.Delete(id);
            return RedirectToAction("Index");
        }

 
    }
}

Mandatory1_MovieCatalog/Views/Movie/Create.cshtml
@model Mandatory1_MovieCatalog.Models.MovieModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    @Html.Partial("_Styles")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <div class="container">
        <h4 class="col-sm-offset-4 col-sm-8">MovieModel</h4>

        @using (Html.BeginForm("CreateConfirmed", "Movie"))
        {
            <div class="form-horizontal">

                @Html.Partial("_MovieForm")

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-10">
                        <input type="submit" value="Create" class="btn btn-primary btn-blue" />
                    </div>
                </div>
            </div>
        }

            <div class="col-sm-offset-4 col-sm-8 green-label">
                @Html.ActionLink("Back to List", "Index")
            </div>
    </div>
</body>
</html>

Mandatory1_MovieCatalog/Views/Movie/Delete.cshtml
@model Mandatory1_MovieCatalog.Models.MovieModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>MovieModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ProductionYear)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProductionYear)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm("DeleteConfirmed", "Movie")) {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.id)

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Mandatory1_MovieCatalog/Views/Movie/Edit.cshtml
@model Mandatory1_MovieCatalog.Models.MovieModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    @Html.Partial("_Styles")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    <div class="container">
        <h4 class="col-sm-offset-4 col-sm-8">MovieModel</h4>

        @using (Html.BeginForm("EditConfirmed", "Movie"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.Partial("_MovieForm")

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary btn-blue" />
                    </div>
                </div>
            </div>
        }

        <div class="col-sm-offset-4 col-sm-8 green-label">
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</body>
</html>

Mandatory1_MovieCatalog/Views/Movie/Index.cshtml
@model IEnumerable<Mandatory1_MovieCatalog.Models.MovieModel>

@*@{
    Layout = null;
}*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
  
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductionYear)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductionYear)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
    }
    
    </table>

    <div class="btn btn-blue">
        @Html.ActionLink("Create New", "Create")
    </div>
</body>
</html>

Mandatory1_MovieCatalog/Views/Movie/_MovieForm.cshtml
@model Mandatory1_MovieCatalog.Models.MovieModel

@Html.ValidationSummary(true, "", new { @class = "color-danger" })
@Html.HiddenFor(model => model.id)

<div class="form-group">
    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-sm-4 green-label" })
    <div class="col-sm-8">
        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Title" } })
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "color-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.ProductionYear, htmlAttributes: new { @class = "control-label col-sm-4 green-label" })
    <div class="col-sm-8">
        @Html.EditorFor(model => model.ProductionYear, new { htmlAttributes = new { @class = "form-control", placeholder = "Production Year" } })
        @Html.ValidationMessageFor(model => model.ProductionYear, "", new { @class = "color-danger" })
    </div>
</div>

Mandatory1_MovieCatalog/Views/Movie/_Styles.cshtml
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald" />
<link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="~/Content/form.css" />